{{- if .Values.onec_server.netHasp.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeonec.fullname" . }}-nethasp
  namespace: {{ .Values.Namespace }}
data:
  nethasp.ini: |
    [NH_COMMON]
    NH_TCPIP = Enabled
    [NH_TCPIP]
    NH_SERVER_ADDR = ["{{ .Values.ones_client.netHasp.serverAddres }}"]
    NH_PORT_NUMBER = 475
    NH_TCPIP_METHOD = UDP
{{- end }}