kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "kubeonec.fullname" . }}-onec-cluster-api
  namespace: {{ .Values.Namespace }}
  labels:
    version: "{{- .Values.onec_server.image.tag}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onec-cluster-api
  template:
    metadata:
      labels:
        app: onec-cluster-api
    spec:
      containers:
        - name: onec-cluster-rac
          image: "{{ .Values.ones_ras.image.repository}}:{{ .Values.ones_ras.image.tag}}"
          command: [ "/opt/1C/v8.3/x86_64/ras", "cluster", "onec-server-kubeonec-service" ]
          imagePullPolicy: Always
          ports: 
            - name: ras
              containerPort: {{ .Values.ones_ras.port }}
              protocol: TCP
          env:
          - name: KUBE_NAMESPACE
            value: {{ .Values.Namespace }}
        - name: ra-api
          image: "{{ .Values.api_cluster_manager.odin.image.repository}}:{{ .Values.api_cluster_manager.odin.image.tag}}"
          imagePullPolicy: Always
          args: 
            - --config
            - /app/odin.yaml
            - --debug
          ports:
            - name: odin-api-port
              containerPort: {{ .Values.api_cluster_manager.odin.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "kubeonec.fullname" . }}-odin-lic
              mountPath: /app/lic/license.lic
              subPath: license.lic
            - name: {{ include "kubeonec.fullname" . }}-odin-conf
              mountPath: /app/odin.yaml
              subPath: odin.yaml
      dnsConfig:
        searches:
          - {{ include "kubeonec.fullname" . }}-hs-service.onec.svc.cluster.local
      volumes:   
        - name: {{ include "kubeonec.fullname" . }}-odin-lic
          secret:
            secretName: odin-lic 
        - name: {{ include "kubeonec.fullname" . }}-odin-conf
          configMap:
            name: {{ include "kubeonec.fullname" . }}-odin-conf                        
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}

---

apiVersion: apps/v1 #  
kind: Deployment
metadata:
  name: {{ include "kubeonec.fullname" . }}-onec-client
  namespace: {{ .Values.Namespace }}
  labels:
    version: " {{- .Values.ones_client.image.tag }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onec-client
  replicas: {{ .Values.ones_client.replicaCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: onec-client
    spec:
      containers:
      - name: onec-client
        image: "{{ .Values.ones_client.image.repository }}:{{ .Values.ones_client.image.tag }}"
        imagePullPolicy: Always
        command: ['sleep', 'infinity']
        # command: ['xstart', 'novnc']
        ports:
          - name: agent
            containerPort: 1543
            protocol: TCP
          - name: novnc
            containerPort: 6080
            protocol: TCP
        volumeMounts:
        - name: {{ include "kubeonec.fullname" . }}-nethasp
          mountPath: /opt/1C/v8.3/x86_64/conf/nethasp.ini
          subPath: nethasp.ini
        env:
        - name: KUBE_NAMESPACE
          value: {{ .Values.Namespace }}
      dnsConfig:
        searches:
          - {{ include "kubeonec.fullname" . }}-hs-service.onec.svc.cluster.local
      volumes:
        - name: {{ include "kubeonec.fullname" . }}-nethasp
          configMap:
            name: {{ include "kubeonec.fullname" . }}-nethasp
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}
