apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-service
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      {{- range   untilStep (int .Values.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
        - protocol: TCP
          name: wp-{{ . }}
          port: {{ (int .) }}
      {{- end }}
        - protocol: TCP
          name: clmen
          port: {{ .Values.serveragent }}
        - protocol: TCP
          name: cluster
          port: {{ .Values.clusterManagerPort }}
        - name: ras
          port: {{ .Values.ones_ras.port }}
  selector:
    app: onec-server
