apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-service
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      {{- range   untilStep (int .Values.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
        - protocol: TCP
          name: wp-{{ . }}
          port: {{ (int .) }}
      {{- end }}
        - protocol: TCP
          name: clmen
          port: {{ .Values.serveragent }}
        - protocol: TCP
          name: cluster
          port: {{ .Values.clusterManagerPort }}
        - name: ras
          port: {{ .Values.ones_ras.port }}
  selector:
    app: onec-server

---


apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-hs-service
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  ports:
      {{- range   untilStep (int .Values.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
        - protocol: TCP
          name: wp-{{ . }}
          port: {{ (int .) }}
      {{- end }}
        - protocol: TCP
          name: clmen
          port: {{ .Values.serveragent }}
        - protocol: TCP
          name: cluster
          port: {{ .Values.clusterManagerPort }}
        - name: ras
          port: {{ .Values.ones_ras.port }}
  clusterIP: None
  selector:
    app: onec-server

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-odin
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
        - protocol: TCP
          name: odin-api-port
          port: 3001
  selector:
    app: onec-cluster-api

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-postges-service
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
        - protocol: TCP
          name: postgresql
          port: {{ .Values.postgres.port }}
  selector:
    app: postgresql

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeonec.fullname" . }}-client
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "kubeonec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
        - name: agent
          protocol: TCP
          port: 1543
        - name: novnc
          protocol: TCP
          port: 6080
  selector:
    app: onec-client
