apiVersion: apps/v1 #  
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}-onec-server
  namespace: {{ .Values.Namespace }}
  labels:
    version: " {{- .Values.onec_server.image.tag }}"
spec:
  serviceName: onec-server
  selector:
    matchLabels:
      app: onec-server
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: onec-server
    spec:
      containers:
      - name: onec-server
        {{- if .Values.onec_server.image.tag }}
        image: "{{ .Values.onec_server.image.repository }}:{{ .Values.onec_server.image.tag }}"
        {{- else }}
        image: "{{ .Values.onec_server.image.repository }}:latest"
        {{- end }}
        ports:
          - name: clmen
            containerPort: {{ .Values.clusterManagerPort }}  
            protocol: TCP
          {{- range untilStep (int .Values.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
          - name: "wp-{{ . }}"
            containerPort: {{ . }}
            protocol: TCP
          {{- end }}
          - name: cluster
            containerPort: {{ .Values.serveragent }}
            protocol: TCP
          - name: ras
            containerPort: {{ .Values.ones_ras.port }}
            protocol: TCP
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}

---

apiVersion: apps/v1 #  
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}-onec-client
  namespace: {{ .Values.Namespace }}
  labels:
    version: " {{- .Values.ones_client.image.tag }}"
spec:
  serviceName: onec-client
  selector:
    matchLabels:
      app: onec-client
  replicas: {{ .Values.ones_client.replicaCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: onec-client
    spec:
      containers:
      - name: onec-client
        image: "{{ .Values.ones_client.image.repository }}:{{ .Values.ones_client.image.tag }}"
        command: ['sleep', 'infinity']
        volumeMounts:
        - name: {{ include "kubeonec.fullname" . }}-nethasp
          mountPath: /opt/1C/v8.3/x86_64/conf/nethasp.ini
          subPath: nethasp.ini
      volumes:
        - name: {{ include "kubeonec.fullname" . }}-nethasp
          configMap:
            name: {{ include "kubeonec.fullname" . }}-nethasp
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}

---

apiVersion: apps/v1 #  
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}-postgres
  namespace: {{ .Values.Namespace }}
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  replicas: {{ .Values.postgres.replicaCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        ports: 
         - name: postgresql
           containerPort: {{ .Values.postgres.port }}
           protocol: TCP
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}


