apiVersion: apps/v1 #  
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}-onec-server
  namespace: {{ .Values.Namespace }}
  labels:
    version: " {{- .Values.onec_server.image.tag }}"
    app: onec-server
spec:
  serviceName: {{ include "kubeonec.fullname" . }}-hs-service
  selector:
    matchLabels:
      app: onec-server
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: onec-server
    spec:
      containers:
      - name: onec-server
        {{- if .Values.onec_server.image.tag }}
        image: "{{ .Values.onec_server.image.repository }}:{{ .Values.onec_server.image.tag }}"
        {{- else }}
        image: "{{ .Values.onec_server.image.repository }}:latest"
        {{- end }}
        ports:
          - name: cluster
            containerPort: {{ .Values.clusterManagerPort }}  
            protocol: TCP
          {{- range untilStep (int .Values.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
          - name: "wp-{{ . }}"
            containerPort: {{ . }}
            protocol: TCP
          {{- end }}
          - name: serveragent
            containerPort: {{ .Values.serveragent }}
            protocol: TCP
          - name: ras
            containerPort: {{ .Values.ones_ras.port }}
            protocol: TCP
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}

---

apiVersion: apps/v1 #  
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}-postgres
  namespace: {{ .Values.Namespace }}
spec:
  serviceName: {{ include "kubeonec.fullname" . }}-postgres-service
  selector:
    matchLabels:
      app: postgresql
  replicas: {{ .Values.postgres.replicaCount }}
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        ports: 
         - name: postgresql
           containerPort: {{ .Values.postgres.port }}
           protocol: TCP
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}
