# Default values for kubeonec.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Namespace: onec

onec_server:
  image:
    repository: demoncat/onec
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: server-8.3.16.1659-k8s
  netHasp: 
    create: true
    serverAddres: 192.168.1.10

ones_ras:
  image:
    repository: demoncat/onec
    tag: full-8-3-14-2095 
  port: 1545

serviceAccount: 
  create: true

imagePullSecrets: [
  "regsecret"
]

nameOverride: ""
fullnameOverride: ""

service: 
  type: ClusterIP

ingress:
  enable: false

# Порты подключения клиентских соединений
workProccesStartPort: 1560
workProccesEndPort: 1591

# Порт подключения менеджера кластера
clusterManagerPort: 1541

