# Default values for kubeonec.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Namespace: onec

onec_version: 8.3.16.1659

postgres:
  image: 
    repository: rsyuzyov/docker-postgresql-pro-1c
    tag: latest
  port: 5432
  replicaCount: 1

onec_server:
  image:
    repository: ghcr.io/thedemoncat/onec-server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 8.3.18.1363

ones_ras:
  image:
    repository: ghcr.io/thedemoncat/onec-full
    tag: 8.3.18.1363 
  port: 1545

ones_client:
  image:
    repository: ghcr.io/thedemoncat/onec-client
    tag:  8.3.18.1363
  replicaCount: 1
  netHasp: 
    create: true
    serverAddres: 192.168.1.1

api_cluster_manager:
  name: odin
  hirac:
    image: 
      repository: 
      tag: latest
    port: 5001
  odin:
    image: 
      repository: ghcr.io/khorevaa/kubodin
      tag: v0.1
    port: 3001

serviceAccount: 
  create: true

imagePullSecrets: [
  "regcred-ghcr-read"
]

nameOverride: ""
fullnameOverride: ""

service: 
  type: ClusterIP

ingress:
  enable: false

# Порты подключения клиентских соединений
workProccesStartPort: 1560
workProccesEndPort: 1591

# Порт подключения менеджера кластера
clusterManagerPort: 1541
# Порт агента сервера (не обязательно, если центральный сервер кластера один).
serveragent: 1540

